# Generated by Django 3.2.20 on 2023-09-04 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('message', models.TextField(max_length=250, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('address1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Address Line 2')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Landmark')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('zipcode', models.CharField(max_length=15, verbose_name='ZIP')),
                ('ordervalue', models.TextField(max_length=1000, verbose_name='Order')),
                ('total', models.IntegerField(verbose_name='Total Amount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pname', models.CharField(max_length=50, verbose_name='Product Name')),
                ('pid', models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('inrdisplay', models.CharField(default='0', max_length=10, verbose_name='Display Price (INR)')),
                ('usddisplay', models.CharField(default='0', max_length=10, verbose_name='Display Price (USD)')),
                ('inrprice', models.IntegerField(default=0, verbose_name='Price (INR)')),
                ('usdprice', models.FloatField(default=0, verbose_name='Price (USD)')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount (%)')),
                ('img0', models.CharField(default='', max_length=30, verbose_name='Image 1')),
                ('img1', models.CharField(default='', max_length=30, verbose_name='Image 2')),
                ('img2', models.CharField(default='', max_length=30, verbose_name='Image 3')),
                ('img3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 4')),
                ('img4', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 5')),
                ('img5', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 6')),
                ('img6', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 7')),
                ('img7', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 8')),
                ('img8', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 9')),
                ('img9', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 10')),
                ('desc', models.TextField(blank=True, max_length=500, null=True, verbose_name='Product Description')),
            ],
        ),
    ]
