# Generated by Django 3.2.20 on 2023-09-02 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pname', models.CharField(max_length=50, verbose_name='Product Name')),
                ('pid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Product ID')),
                ('inrdisplay', models.IntegerField(default=0, verbose_name='Display Price (INR)')),
                ('usddisplay', models.FloatField(default=0, verbose_name='Display Price (USD)')),
                ('inrprice', models.IntegerField(default=0, verbose_name='Price (INR)')),
                ('usdprice', models.FloatField(default=0, verbose_name='Price (USD)')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount (%)')),
                ('img0', models.CharField(default='', max_length=30, verbose_name='Image 1')),
                ('img1', models.CharField(default='', max_length=30, verbose_name='Image 2')),
                ('img2', models.CharField(default='', max_length=30, verbose_name='Image 3')),
                ('img3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 4')),
                ('img4', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 5')),
                ('img5', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 6')),
                ('img6', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 7')),
                ('img7', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 8')),
                ('img8', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 9')),
                ('img9', models.CharField(blank=True, max_length=30, null=True, verbose_name='Image 10')),
            ],
        ),
    ]
