# Generated by Django 3.2.20 on 2023-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Product Description'),
        ),
    ]
