# Generated by Django 3.2.20 on 2023-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0002_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.UUIDField(default='ec2fd4a60f0d496a983d072f3e659e14', primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
