# Generated by Django 3.2.20 on 2023-09-02 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0003_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.UUIDField(default=uuid.UUID('2fe8236e-cfc6-4da7-b503-f22e18ade397'), primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
