# Generated by Django 3.2.20 on 2023-09-02 13:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0006_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('091aa9ed-4675-4939-a538-4484f66897ba'), max_length=40, primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
