# Generated by Django 3.2.20 on 2023-09-02 13:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0007_alter_product_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inrdisplay',
            field=models.CharField(default='0', max_length=10, verbose_name='Display Price (INR)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('2c95529f-7a56-45e2-be4e-72f87ff1bec5'), max_length=40, primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usddisplay',
            field=models.CharField(default='0', max_length=10, verbose_name='Display Price (USD)'),
        ),
    ]
