# Generated by Django 3.2.20 on 2023-09-03 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0008_auto_20230902_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('address1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('address2', models.CharField(blank=True, max_length=100, verbose_name='Address Line 2')),
                ('landmark', models.CharField(blank=True, max_length=100, verbose_name='Landmark')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('zipcode', models.CharField(max_length=15, verbose_name='ZIP')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('00848cf0-f641-4d0f-99d4-fa702e28e927'), max_length=40, primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
