# Generated by Django 3.2.20 on 2023-09-04 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0010_auto_20230904_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordervalue',
            field=models.TextField(default='', max_length=1000, verbose_name='Order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total Amount:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=250, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('5157310d-201d-4176-8ee2-edc446f530ae'), max_length=40, primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
