# Generated by Django 3.2.20 on 2023-09-04 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stradaapp', '0012_auto_20230904_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.CharField(default=uuid.UUID('c3ebdde3-0e24-4a90-9af1-863888d72a45'), max_length=40, primary_key=True, serialize=False, verbose_name='Product ID'),
        ),
    ]
